import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="flex h-16 bg-yellow-300 ">
          <form
            action="/items"
            className=" m-auto flex max-w-screen-xl flex-1 gap-4 px-4"
          >
            <Link href="/" className="text-yellow-900 items-center">
              Mercado
            </Link>
            <input
              name="search"
              type="text"
              className="h-8 flex-1 px-2 py-1 text-white"
            ></input>

            <button className="h-8 bg-gray-300 px-2 py-1  text-slate-700">
              Buscar
            </button>
          </form>
        </header>
        <main className=" m-auto max-w-screen-lg p-4">{children}</main>
      </body>
    </html>
  );
}
